server:
  port: 8001
#  servlet:
#    context-path: /api

eip:
  api:
    doc:
      swagger:
        enabled: true
        group-name: business
        title: "昂立课堂(业务版)"
        version: 1.0.0
        contact:
          name: 朱增亮
          emial: zhangsan@163.com
          url: http://localhost:8001/doc.html#/home
        description: "昂立课堂第二版，在SDK版上升级了业务模块，业务模块包括：用户、老师、学生、课程、课节、上课统计流水等。"
        host: http://localhost:1111
  lock:
    redisson:
      server:
        type: STANDALONE
        address: 192.168.100.54:6379
        database: 2
        password: 123456
knife4j:
  enable: true
  production: false #生产环境屏蔽所有swagger资源
  basic:
    enable: true   #开启账号密码验证
    username: admin
    password: admin
spring:
  redis:
    host: 192.168.100.54
    database: 7
    password: 123456
  application:
    name: eip-business-web
  profiles:
    active: '@my-profile@'


eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUEEKA_SERVER_URL:http://localhost:9001/eureka/}
  instance:
    hostname: ${spring.cloud.client.ip-address} #服务注册中心地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    metadata-map:
#      user.name: ${spring.security.user.name}
#      user.password: ${spring.security.user.password}
#      startup: ${random.int}    #needed to trigger info and endpoint update after restart


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#logback日志配置
logging:
  file: #springboot admin动态日志
    path: ./logs
    name: ./logs/${spring.application.name}-all.log
  level:
    root: info
  config: classpath:logback/spring-logback.xml
log:
  path: ./logs
  name: eip-business-web