server:
  port: 3001

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: oauth2-cloud-gateway
  cloud:
    gateway:
      ## 路由
      routes:
      ## id只要唯一即可，名称任意
      - id: oauth2-cloud-auth-server
        uri: http://localhost:3002
        predicates:
        ## Path Route Predicate Factory断言
        - Path=/oauth/**
      - id: oauth2-cloud-order
        uri: http://localhost:9002
        predicates:
        ## Path Route Predicate Factory断言
        - Path=/resources/**
        filters:
          - StripPrefix=1

  redis:
    host: 192.168.100.54
    port: 6379
    database: 1
    password: 123456
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10

eip:
  gateway:
    sys:
      ignoreUrls:
      - /oauth/token
      - /oauth/authorize