server:
  port: 10003
spring:
  application:
    name: service-doc
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#      routes:
#      - id: quoted-server
#        uri: lb://quoted-server
#        predicates:
#        - Path=/api/quoted/**
#        - Header=Cookie,Set-Cookie
#        filters:
#        - SwaggerHeaderFilter
#        - StripPrefix=2
#      - id:  service-order
#        uri: lb://service-order
#        predicates:
#        - Path=/order/**
#        filters:
#        - SwaggerHeaderFilter
#        - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

logging:
  level:
    org.springframework:cloud.gateway: debug


com:
  eip:
    swagger:
      gateway:
        ingore-server-list:
          - eureka-server
          - service-doc
        server-alias-list:
          - server-name: quoted-server
            server-alias: 报价服务

