eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false # 自我保护模式关闭
    eviction-interval-timer-in-ms: 5000 # 主动失效检测间隔,配置成5秒
    response-cache-update-interval-ms: 3000 #禁用readOnlyCacheMap
    use-read-only-response-cache: false #禁用readOnlyCacheMap
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: localhost
    lease-expiration-duration-in-seconds: 15 #服务过期时间配置,个配置一般为服务刷新时间配置的三倍
    lease-renewal-interval-in-seconds: 5 #服务刷新时间配置，每隔这个时间会主动心跳一次，默认30s
server:
  port: 8761
