eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address} #服务注册中心地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5 #服务续约任务的调用时间间隔，默认30秒。客户端不配置，默认走server端配置
    lease-expiration-duration-in-seconds: 10 #服务失效时间，默认90秒。客户端不配置，默认走server端配置
  client:
    registry-fetch-interval-seconds: 5 #从Eureka Server服务端获取注册信息的间隔时间，单位：秒
    service-url:
      defaultZone: ${EUEEKA_SERVER_URL:http://localhost:9001/eureka/}

