server:
  port: 3001

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: oauth2-cloud-gateway
  cloud:
    gateway:
      enabled: true
      # 当service实例不存在时默认返回503，显示配置返回404
      loadbalancer:
        use404: true
      # 效果：/serviceId/path1/args ==> /path1/arg
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      ## 路由
      routes:
      - id: oauth2-cloud-order
        uri: http://localhost:9002
        predicates:
        ## Path Route Predicate Factory断言
        - Path=/res/**
        filters:
          - StripPrefix=1

  redis:
    host: 192.168.100.xxx
    port: 6379
    database: 1
    password: 123456
    timeout: 15000
    jedis:
      pool:
        max-active: 600
        max-idle: 300
        max-wait: 15000
        min-idle: 10

eip:
  gateway:
    sys:
      ignoreUrls:
      - /oauth/token
      - /oauth/authorize